# Generated by Django 3.2.4 on 2021-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='media',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
